import Head from 'next/head';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import ListItemRepository from '../components/dumb/ListItem/Repository';

// PAGE
export default function Home() {
  return (
    <Box
      minHeight="100vh"
      px={1}
      display="flex"
      flexDirection="column"
      alignItems="center"
      justifyContent="center"
    >
      <Head>
        <title>Github Indicators Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        component="main"
        display="flex"
        flexDirection="column"
        alignItems="center"
        justifyContent="center"
        flexGrow={1}
      >
        <Typography
          variant="h3"
          paragraph
          sx={{
            fontWeight: 'bold',
          }}
        >
          Github Indicators Explorer

        </Typography>
        <Typography
          variant="subtitle1"
        >
          Github Indicators Explorer can help you get key metrics
          about your favourite github repositories
        </Typography>
      </Box>
      <ListItemRepository fullName="traefik/mesh" description="Traefik Mesh - Simpler Service Mesh" ownerAvatarUrl="vercel.svg" />
    </Box>
  );
}
